Repository django-cms/django-cms, pull requests merged in 2018-06, with the labels that each got.

#6368 Fixed #6346 -- Set xframe options exempt on cached response
  AUTHORS
  CHANGELOG.txt
  cms/tests/test_page.py
  cms/views.py
Labels: needs to be backported, needs to be forwardported, status: accepted, status: ready for review

#6404 Fixed #6346 -- Set xframe options exempt on cached response
  AUTHORS
  CHANGELOG.txt
  cms/tests/test_page.py
  cms/views.py
Labels: backport, status: accepted

#6403 Fixed #6346 -- Set xframe options exempt on cached response
  AUTHORS
  cms/tests/test_page.py
  cms/views.py
Labels: forwardport, status: accepted

#6255 Update apphooks.rst
  docs/how_to/apphooks.rst
Labels: component: documentation, status: accepted

#6370 Fixed #6335 -- Global permissions should take precedence over cached page permissions
  CHANGELOG.txt
  cms/tests/test_permissions.py
  cms/utils/page_permissions.py
Labels: needs to be backported, status: accepted, status: ready for review

#6411 Fixed #6335 -- Global permissions take precedence over cached page permissions
  cms/tests/test_permissions.py
  cms/utils/page_permissions.py
Labels: forwardport, status: accepted

#6410 Fixed #6335 -- Global permissions take precedence over cached page permissions
  CHANGELOG.txt
  cms/tests/test_permissions.py
  cms/utils/page_permissions.py
Labels: backport, status: accepted

#6415 Disabled frontend tests
  .travis.yml
Labels: status: accepted

#6414 Remove Publish button from the toolbar
  cms/cms_toolbars.py
  cms/tests/test_toolbar.py
Labels: status: accepted

#6122 Added page_title parameter to cms.api.create_page() and cms.api.create_title().
  CHANGELOG.txt
  cms/api.py
  cms/tests/test_api.py
  docs/reference/api_references.rst
Labels: status: accepted

#6389 Fixed a bug with not enabling plugins that are not rendered in content
  cms/static/cms/js/dist/3.5.2/bundle.toolbar.min.js
  cms/static/cms/js/modules/cms.structureboard.js
  cms/tests/frontend/unit/cms.structureboard.test.js
Labels: needs to be backported

#6418 Fixed a bug with expanding static placeholder by clicking on "Expand All" button
  cms/static/cms/js/dist/3.5.2/bundle.toolbar.min.js
  cms/static/cms/js/modules/cms.plugins.js
Labels: component: frontend, needs to be backported, needs to be forwardported

#6417 Fixed a bug with not enabling plugins that are not rendered in content
  CHANGELOG.txt
  cms/static/cms/js/dist/3.5.2/bundle.toolbar.min.js
  cms/static/cms/js/modules/cms.structureboard.js
  cms/tests/frontend/unit/cms.structureboard.test.js
Labels: backport

#6420 Fixed a bug with expanding static placeholder by clicking on "Expand All" button
  CHANGELOG.txt
  cms/static/cms/js/dist/3.5.2/bundle.toolbar.min.js
  cms/static/cms/js/modules/cms.plugins.js
Labels: backport

#6423 Fixed a bug with not enabling plugins that are not rendered in content
  cms/static/cms/js/dist/3.5.2/bundle.toolbar.min.js
  cms/static/cms/js/modules/cms.structureboard.js
  cms/tests/frontend/unit/cms.structureboard.test.js
Labels: forwardport

#6422 Fixed a bug with expanding static placeholder by clicking on "Expand All" button
  cms/static/cms/js/dist/3.5.2/bundle.toolbar.min.js
  cms/static/cms/js/modules/cms.plugins.js
Labels: forwardport

#6425 Added request to page create form
  cms/admin/forms.py
  cms/admin/pageadmin.py
  cms/forms/wizards.py
  cms/tests/test_admin.py
  cms/tests/test_apphooks.py
  cms/tests/test_wizards.py
  cms/wizards/forms.py
  cms/wizards/views.py
Labels: status: accepted
