Repository django-cms/django-cms, pull requests merged in 2018-08, with the labels that each got.

#6465 Placeholder admin configure urls views
  cms/admin/placeholderadmin.py
  cms/test_utils/testcases.py
  cms/tests/test_placeholder_admin.py
Labels: status: accepted

#6461 Provide MySQL and SQLite compat for Refactored plugin tree (#6437)
  cms/models/placeholdermodel.py
  cms/models/pluginmodel.py
  cms/tests/test_rendering.py
Labels: status: accepted

#6412 Fixed #6383 -- Rewriting url of page corrupted after save basic settings of page
  CHANGELOG.txt
  cms/admin/forms.py
  cms/tests/test_page_admin.py
Labels: status: accepted

#6470 Fixed #6383 -- Rewriting url of page corrupted after save basic settings of page
  CHANGELOG.txt
  cms/admin/forms.py
  cms/tests/test_page_admin.py
Labels: forwardport, status: accepted

#6468 Remove default plugin creation
  cms/tests/test_permmod.py
  cms/tests/test_placeholder.py
  cms/tests/test_rendering.py
  cms/utils/plugins.py
  docs/reference/configuration.rst
  docs/upgrade/3.0.rst
Labels: status: accepted

#6469 Replace plugin endpoints with placeholder endpoints
  cms/admin/__init__.py
  cms/admin/pageadmin.py
  cms/admin/placeholderadmin.py
  cms/admin/settingsadmin.py
  cms/admin/static_placeholder.py
  cms/models/placeholdermodel.py
  cms/models/pluginmodel.py
  cms/plugin_base.py
  cms/templates/admin/cms/page/plugin/submit_line.html
  cms/templates/cms/toolbar/plugin.html
  cms/templates/cms/toolbar/toolbar_javascript.html
  cms/test_utils/project/placeholderapp/admin.py
  cms/test_utils/project/sampleapp/admin.py
  cms/test_utils/testcases.py
  cms/tests/test_admin.py
  cms/tests/test_alias.py
  cms/tests/test_log_entries.py
  cms/tests/test_permmod.py
  cms/tests/test_placeholder.py
  cms/tests/test_placeholder_admin.py
  cms/tests/test_placeholder_app_admin.py
  cms/tests/test_placeholder_operation_signals.py
  cms/tests/test_plugins.py
  cms/tests/test_security.py
  cms/tests/test_static_placeholder.py
  cms/tests/test_toolbar.py
  cms/toolbar/utils.py
Labels: status: accepted

#6477 Move select Page fields to Title
  cms/admin/forms.py
  cms/admin/pageadmin.py
  cms/api.py
  cms/cms_menus.py
  cms/cms_toolbars.py
  cms/forms/wizards.py
  cms/migrations/0001_initial.py
  cms/migrations/0029_create_title_fields_to_be_moved_from_page.py
  cms/migrations/0030_migrate_fields_from_page_to_title.py
  cms/migrations/0031_remove_page_fields.py
  cms/models/pagemodel.py
  cms/models/titlemodels.py
  cms/page_rendering.py
  cms/tests/test_admin.py
  cms/tests/test_api.py
  cms/tests/test_menu.py
  cms/tests/test_navextender.py
  cms/tests/test_page.py
  cms/tests/test_page_admin.py
  cms/tests/test_publisher.py
  cms/tests/test_rendering.py
  cms/tests/test_templatetags.py
  cms/tests/test_views.py
  cms/tests/test_wizards.py
Labels: status: accepted

#6491 Use new edit structure urls in frontend
  cms/static/cms/js/dist/4.0.0dev1/bundle.toolbar.min.js
  cms/static/cms/js/modules/cms.structureboard.js
  cms/static/cms/js/modules/cms.toolbar.js
  cms/tests/frontend/integration/add-multiple-plugins.js
  cms/tests/frontend/integration/link-plugin-content-mode.js
  cms/tests/frontend/integration/modal.js
  cms/tests/frontend/unit/cms.structureboard.test.js
  cms/tests/frontend/unit/cms.toolbar.test.js
Labels: component: frontend
