Repository django-cms/django-cms, pull requests merged in 2018-07, with the labels that each got.

#6419 Log operations
  cms/admin/forms.py
  cms/admin/pageadmin.py
  cms/operations/__init__.py
  cms/operations/helpers.py
  cms/signals/__init__.py
  cms/signals/log_entries.py
  cms/tests/test_admin.py
  cms/tests/test_log_entries.py
Labels: kind: enhancement, status: accepted, status: ready for review

#6431 Fixed #6296 -- Removed localization for pk values in toolbar js (#6294)
  CHANGELOG.txt
  cms/templates/cms/toolbar/toolbar_javascript.html
Labels: backport

#6284 Fixes #5828 - Create page wizard on new site works inconsistently
  CHANGELOG.txt
  cms/wizards/views.py
Labels: status: accepted

#6436 Integrate wizards with app registration
  cms/app_registration.py
  cms/cms_config.py
  cms/cms_wizards.py
  cms/test_utils/project/backwards_wizards/__init__.py
  cms/test_utils/project/backwards_wizards/cms_wizards.py
  cms/test_utils/project/backwards_wizards/wizards.py
  cms/test_utils/project/sampleapp/cms_config.py
  cms/test_utils/project/sampleapp/cms_wizards.py
  cms/test_utils/project/sampleapp/forms.py
  cms/tests/test_cms_config_wizards.py
  cms/tests/test_wizards.py
  cms/utils/setup.py
  cms/wizards/helpers.py
  cms/wizards/wizard_pool.py
Labels: kind: enhancement, status: accepted, status: work in progress

#6442 Moved placeholders from Page to Title model
  cms/admin/forms.py
  cms/admin/pageadmin.py
  cms/admin/settingsadmin.py
  cms/api.py
  cms/forms/wizards.py
  cms/migrations/0022_title_placeholders.py
  cms/migrations/0023_title_placeholders_data_migration.py
  cms/migrations/0024_remove_page_placeholders.py
  cms/models/pagemodel.py
  cms/models/placeholdermodel.py
  cms/models/titlemodels.py
  cms/plugin_rendering.py
  cms/sitemaps/cms_sitemap.py
  cms/templates/cms/toolbar/structure.html
  cms/templatetags/cms_js_tags.py
  cms/templatetags/cms_tags.py
  cms/tests/test_admin.py
  cms/tests/test_alias.py
  cms/tests/test_cache.py
  cms/tests/test_log_entries.py
  cms/tests/test_management.py
  cms/tests/test_multilingual.py
  cms/tests/test_nested_plugins.py
  cms/tests/test_no_i18n.py
  cms/tests/test_page.py
  cms/tests/test_page_admin.py
  cms/tests/test_permmod.py
  cms/tests/test_placeholder.py
  cms/tests/test_placeholder_operation_signals.py
  cms/tests/test_plugin_renderers.py
  cms/tests/test_plugins.py
  cms/tests/test_publisher.py
  cms/tests/test_rendering.py
  cms/tests/test_security.py
  cms/tests/test_templatetags.py
  cms/tests/test_toolbar.py
  cms/tests/test_views.py
  cms/utils/page_permissions.py
  cms/utils/plugins.py
  cms/views.py
Labels: kind: enhancement, status: accepted

#6438 Removed unpublish button from toolbar
  cms/cms_toolbars.py
Labels: status: accepted

#6445 Remove publish / unpublish buttons from page changelist
  cms/templates/admin/cms/page/tree/menu.html
  cms/templatetags/cms_admin.py
Labels: status: accepted

#6453 Remove publisher_publish command
  cms/management/commands/cms.py
  cms/management/commands/subcommands/publisher_publish.py
  cms/tests/test_management.py
  cms/tests/test_publisher.py
Labels: status: accepted

#6454 Remove revert to live feature
  cms/admin/pageadmin.py
  cms/cms_toolbars.py
  cms/models/pagemodel.py
  cms/tests/test_page.py
  cms/tests/test_page_admin.py
  cms/tests/test_publisher.py
  cms/utils/page_permissions.py
Labels: status: accepted

#6452 Fil 190: Adding Generic Foreign Key to Placeholder model
  cms/migrations/0023_auto_20180719_1638.py
  cms/migrations/0024_title_placeholders.py
  cms/migrations/0025_title_placeholders_data_migration.py
  cms/migrations/0026_remove_page_placeholders.py
  cms/models/placeholdermodel.py
Labels: status: accepted

#6427 Rewrote how-to guide and reference for the toolbar
  cms/middleware/toolbar.py
  docs/how_to/toolbar.rst
  docs/introduction/05-apphooks.rst
  docs/introduction/06-toolbar.rst
  docs/reference/configuration.rst
  docs/reference/toolbar.rst
Labels: component: documentation
