Repository django-cms/django-cms, pull requests merged in 2018-05, with the labels that each got.

#6350 Fixed #6336 -- request.current_page should always respect draft/live state
  cms/appresolver.py
  cms/test_utils/project/sampleapp/cms_apps.py
  cms/tests/test_apphooks.py
Labels: status: accepted

#6354 Fixed #6336 -- request.current_page should always respect draft/live state
  CHANGELOG.txt
  cms/appresolver.py
  cms/test_utils/project/sampleapp/cms_apps.py
  cms/tests/test_apphooks.py
Labels: backport, needs to be backported, status: accepted

#6362 Refs #6185 -- Moved meta description length restriction from model to form
  CHANGELOG.txt
  cms/admin/forms.py
  cms/migrations/0021_auto_20180507_1432.py
  cms/models/titlemodels.py
  docs/user/reference/page_admin.rst
Labels: status: accepted, status: ready for review

#6369 Fixed #6002 -- Prevent users from moving homepage under another page
  cms/admin/forms.py
  cms/tests/test_page_admin.py
Labels: needs to be backported, status: accepted, status: ready for review

#6375 Fix and update some links at the README
  README.rst
Labels: component: documentation, kind: cleanup, status: accepted

#6366 Removed extra quotation mark from button sideframe template
  CHANGELOG.txt
  cms/templates/cms/toolbar/items/button_sideframe.html
Labels: backport, status: accepted

#6334 Fixed a bug with incorrect move plugin handling
  CHANGELOG.txt
  cms/static/cms/js/dist/3.5.2/bundle.admin.base.min.js
  cms/static/cms/js/dist/3.5.2/bundle.admin.changeform.min.js
  cms/static/cms/js/dist/3.5.2/bundle.admin.pagetree.min.js
  cms/static/cms/js/dist/3.5.2/bundle.admin.widget.min.js
  cms/static/cms/js/dist/3.5.2/bundle.forms.apphookselect.min.js
  cms/static/cms/js/dist/3.5.2/bundle.forms.pageselectwidget.min.js
  cms/static/cms/js/dist/3.5.2/bundle.forms.pagesmartlinkwidget.min.js
  cms/static/cms/js/dist/3.5.2/bundle.forms.slugwidget.min.js
  cms/static/cms/js/dist/3.5.2/bundle.toolbar.min.js
  cms/static/cms/js/modules/cms.structureboard.js
  cms/tests/frontend/unit/cms.structureboard.test.js
Labels: needs to be backported

#6386 Fixed a bug where structureboard tried to preload markup with legacy renderer
  CHANGELOG.txt
  cms/static/cms/js/dist/3.5.2/bundle.toolbar.min.js
  cms/static/cms/js/modules/cms.structureboard.js
  cms/static/cms/js/modules/preload-images.js
  cms/tests/frontend/unit/cms.structureboard.test.js
  cms/tests/frontend/unit/index.js
  cms/tests/frontend/unit/preload-images.test.js
Labels: backport, component: frontend

#6387 Fixed a bug with incorrect move plugin handling
  CHANGELOG.txt
  cms/static/cms/js/dist/3.5.2/bundle.admin.base.min.js
  cms/static/cms/js/dist/3.5.2/bundle.admin.changeform.min.js
  cms/static/cms/js/dist/3.5.2/bundle.admin.pagetree.min.js
  cms/static/cms/js/dist/3.5.2/bundle.admin.widget.min.js
  cms/static/cms/js/dist/3.5.2/bundle.forms.apphookselect.min.js
  cms/static/cms/js/dist/3.5.2/bundle.forms.pageselectwidget.min.js
  cms/static/cms/js/dist/3.5.2/bundle.forms.pagesmartlinkwidget.min.js
  cms/static/cms/js/dist/3.5.2/bundle.forms.slugwidget.min.js
  cms/static/cms/js/dist/3.5.2/bundle.toolbar.min.js
  cms/static/cms/js/modules/cms.structureboard.js
  cms/tests/frontend/unit/cms.structureboard.test.js
Labels: backport

#6391 Fixed some spelling and build issues
  docs/conf.py
  docs/how_to/toolbar.rst
  docs/reference/api_references.rst
  docs/reference/configuration.rst
  docs/reference/navigation.rst
  docs/reference/templatetags.rst
  docs/requirements.txt
  docs/spelling_wordlist
  docs/topics/permissions.rst
  docs/upgrade/3.3.rst
  docs/upgrade/3.4.1.rst
  docs/upgrade/3.4.2.rst
  docs/upgrade/3.4.rst
  docs/upgrade/3.5.2.rst
Labels: component: documentation

#6390 Fixes/improves introductory tutorial
  docs/introduction/01-install.rst
  docs/introduction/02-templates_placeholders.rst
  docs/introduction/03-integrating_applications.rst
  docs/introduction/04-plugins.rst
  docs/introduction/05-apphooks.rst
  docs/introduction/06-toolbar.rst
  docs/introduction/07-menu.rst
  docs/introduction/08-wizards.rst
  docs/introduction/09-third_party.rst
  docs/introduction/images/welcome.png
  docs/introduction/index.rst
  docs/introduction/plugins.rst
Labels: component: documentation
