Repository django-cms/django-cms, pull requests merged in 2018-09, with the labels that each got.

#6496 Placeholder source field implementation
  cms/admin/pageadmin.py
  cms/forms/utils.py
  cms/migrations/0033_placeholder_source_data_migration.py
  cms/migrations/0034_remove_pagecontent_placeholders.py
  cms/models/fields.py
  cms/models/managers.py
  cms/models/pagemodel.py
  cms/models/placeholdermodel.py
  cms/models/titlemodels.py
  cms/plugin_rendering.py
  cms/templatetags/cms_js_tags.py
  cms/templatetags/cms_tags.py
  cms/test_utils/project/placeholder_relation_field_app/__init__.py
  cms/test_utils/project/placeholder_relation_field_app/admin.py
  cms/test_utils/project/placeholder_relation_field_app/models.py
  cms/test_utils/project/placeholder_relation_field_app/templates/fancy_poll_app/detail.html
  cms/test_utils/project/placeholder_relation_field_app/templates/fancy_poll_app/detail2.html
  cms/test_utils/project/placeholder_relation_field_app/urls.py
  cms/test_utils/project/placeholder_relation_field_app/views.py
  cms/test_utils/project/urls.py
  cms/tests/test_cache.py
  cms/tests/test_page.py
  cms/tests/test_page_admin.py
  cms/tests/test_placeholder.py
  cms/tests/test_rendering.py
  cms/tests/test_templatetags.py
  cms/tests/test_toolbar.py
  cms/toolbar/toolbar.py
  cms/utils/placeholder.py
  cms/views.py
  manage.py
Labels: status: accepted

#6503 Added PageContent admin
  cms/admin/forms.py
  cms/admin/pageadmin.py
  cms/admin/permissionadmin.py
  cms/cms_toolbars.py
  cms/forms/validators.py
  cms/forms/wizards.py
  cms/migrations/0032_remove_title_to_pagecontent.py
  cms/models/pagemodel.py
  cms/models/titlemodels.py
  cms/templates/admin/cms/page/change_form.html
  cms/templates/admin/cms/page/submit_row.html
  cms/templates/admin/cms/page/tree/actions_dropdown.html
  cms/templates/admin/cms/page/tree/base.html
  cms/templates/admin/cms/page/tree/menu.html
  cms/templatetags/cms_admin.py
  cms/test_utils/project/templates/sidebar_submenu.html
  cms/test_utils/testcases.py
  cms/tests/test_admin.py
  cms/tests/test_extensions.py
  cms/tests/test_forms.py
  cms/tests/test_log_entries.py
  cms/tests/test_multilingual.py
  cms/tests/test_no_i18n.py
  cms/tests/test_page.py
  cms/tests/test_page_admin.py
  cms/tests/test_permmod.py
  cms/tests/test_plugins.py
  cms/tests/test_signals.py
  cms/tests/test_site.py
  cms/tests/test_toolbar.py
  cms/tests/test_widgets.py
  cms/tests/test_wizards.py
Labels: status: accepted

#6505 Add placeholder checks
  cms/admin/placeholderadmin.py
  cms/models/fields.py
  cms/models/placeholdermodel.py
  cms/tests/test_placeholder_checks.py
Labels: status: accepted

#6473 Fixes/load fixture
  cms/models/pagemodel.py
  cms/signals/page.py
Labels: status: accepted

#6501 Fixed a bug with deleting a model from changelist inside modal
  CHANGELOG.txt
  cms/static/cms/js/dist/3.5.2/bundle.toolbar.min.js
  cms/static/cms/js/modules/cms.modal.js
Labels: component: frontend, needs to be forwardported

#6531 Expose sideframe in CMS.API
  cms/static/cms/js/dist/4.0.0dev5/bundle.toolbar.min.js
  cms/static/cms/js/modules/cms.sideframe.js
  cms/static/cms/js/modules/cms.toolbar.js
  cms/templates/cms/toolbar/toolbar_javascript.html
  cms/tests/frontend/unit/cms.sideframe.test.js
Labels: component: frontend
