Repository django-cms/django-cms, pull requests merged in 2019-11, with the labels that each got.

#6224 Improved and simplified permissions documentation
  docs/topics/permissions.rst
Labels: component: documentation

#6320 Updated branch policy
  README.rst
  docs/contributing/development-policies.rst
Labels: component: documentation

#6744 Fix documentation bug regarding CMSPluginBase
  docs/reference/plugins.rst
Labels: component: documentation, status: accepted

#6609 Added example of `get_plugin_instance` to the docs on nested plugins.
  docs/how_to/custom_plugins.rst
Labels: component: documentation, status: accepted

#6679 Sites - Pass Site obj instead of pk when creating a StaticPlaceholder
  AUTHORS
  CHANGELOG.txt
  cms/templatetags/cms_js_tags.py
  cms/test_utils/project/templates/placeholder_tests/static_with_site.html
  cms/tests/test_site.py
Labels: status: accepted

#6705 Do not let non-staff users to log in via CMS Toolbar
  cms/forms/login.py
  cms/tests/test_toolbar.py
Labels: status: accepted
