Repository django-cms/django-cms, pull requests merged in 2019-03, with the labels that each got.

#6629 Fixed travis matrix by moving menu test to allow_failures section
  .travis.yml
Labels: backport

#6497 Fixed #6492 -- Object / embed tags in top-level plugins
  cms/static/cms/js/dist/3.6.0/bundle.admin.base.min.js
  cms/static/cms/js/dist/3.6.0/bundle.admin.changeform.min.js
  cms/static/cms/js/dist/3.6.0/bundle.admin.pagetree.min.js
  cms/static/cms/js/dist/3.6.0/bundle.admin.widget.min.js
  cms/static/cms/js/dist/3.6.0/bundle.forms.apphookselect.min.js
  cms/static/cms/js/dist/3.6.0/bundle.forms.pageselectwidget.min.js
  cms/static/cms/js/dist/3.6.0/bundle.forms.pagesmartlinkwidget.min.js
  cms/static/cms/js/dist/3.6.0/bundle.forms.slugwidget.min.js
  cms/static/cms/js/dist/3.6.0/bundle.toolbar.min.js
  cms/static/cms/js/modules/cms.plugins.js
  cms/tests/frontend/unit/cms.plugins.test.js
  cms/tests/frontend/unit/fixtures/plugins_complex_markup.html
Labels: component: frontend, needs to be backported

#6472 Fixed #6440 -- render_plugin_block template tag
  cms/templates/cms/toolbar/render_plugin_block.html
  cms/templatetags/cms_tags.py
Labels: status: accepted

#6330 typo: added spaces on configuration docs
  docs/reference/configuration.rst
Labels: component: documentation

#6647 typo: added spaces on configuration docs (#6330)
  docs/reference/configuration.rst
Labels: backport

#6643 Fixed #6440 -- render_plugin_block template tag (#6472)
  cms/templates/cms/toolbar/render_plugin_block.html
  cms/templatetags/cms_tags.py
Labels: backport

#6638 Update copyright year in docs to be dynamic (#6618)
  docs/conf.py
Labels: backport

#6634 Fix typo in documentation (#6612)
  docs/introduction/05-apphooks.rst
  docs/introduction/index.rst
Labels: backport

#6635 Update install documentation to use re_path (#6613)
  docs/how_to/install.rst
Labels: backport

#6633 Update install.rst
  docs/how_to/install.rst
Labels: backport

#6630 Fixed a bug with top-level object/embed/applet tags (#6497)
  cms/static/cms/js/dist/3.6.0/bundle.admin.base.min.js
  cms/static/cms/js/dist/3.6.0/bundle.admin.changeform.min.js
  cms/static/cms/js/dist/3.6.0/bundle.admin.pagetree.min.js
  cms/static/cms/js/dist/3.6.0/bundle.admin.widget.min.js
  cms/static/cms/js/dist/3.6.0/bundle.forms.apphookselect.min.js
  cms/static/cms/js/dist/3.6.0/bundle.forms.pageselectwidget.min.js
  cms/static/cms/js/dist/3.6.0/bundle.forms.pagesmartlinkwidget.min.js
  cms/static/cms/js/dist/3.6.0/bundle.forms.slugwidget.min.js
  cms/static/cms/js/dist/3.6.0/bundle.toolbar.min.js
  cms/static/cms/js/modules/cms.plugins.js
  cms/tests/frontend/unit/cms.plugins.test.js
  cms/tests/frontend/unit/fixtures/plugins_complex_markup.html
Labels: backport

#6631 Fix wrong field name
  docs/how_to/extending_page_title.rst
Labels: backport

#6641 Page has no attribute site_id [Docs] (#6614)
  docs/how_to/extending_page_title.rst
Labels: backport

#6648 typo: added spaces on configuration docs (#6330)
  docs/reference/configuration.rst
Labels: backport

#6654 Fixed djangocms-text-ckeditor version for older Django versions (#6651)
  .travis.yml
  test_requirements/django-1.10.txt
  test_requirements/django-1.11.txt
  test_requirements/django-1.8.txt
  test_requirements/django-1.9.txt
  test_requirements/requirements_base.txt
Labels: backport

#6644 Fixed #6440 -- render_plugin_block template tag (#6472)
  cms/templates/cms/toolbar/render_plugin_block.html
  cms/templatetags/cms_tags.py
Labels: backport

#6642 Page has no attribute site_id [Docs] (#6614)
  docs/how_to/extending_page_title.rst
Labels: backport

#6639 Update copyright year in docs to be dynamic (#6618)
  docs/conf.py
Labels: backport

#6632 Fix wrong field name
  docs/how_to/extending_page_title.rst
Labels: backport

#6649 typo: added spaces on configuration docs (#6330)
  docs/reference/configuration.rst
Labels: backport

#6645 Fixed #6440 -- render_plugin_block template tag (#6472)
  cms/templates/cms/toolbar/render_plugin_block.html
  cms/templatetags/cms_tags.py
Labels: backport

#6640 Update copyright year in docs to be dynamic (#6618)
  docs/conf.py
Labels: backport
