Repository django-cms/django-cms, pull requests merged in 2020-05, with the labels that each got.

#6854 Move var declaration inside closure to make it available to firefox
  CHANGELOG.rst
  cms/static/cms/js/widgets/forms.apphookselect.js
Labels: component: frontend, kind: bug

#6798 Corrected plugin documentations based on Issue #6752
  CHANGELOG.rst
  docs/how_to/custom_plugins.rst
Labels: component: documentation

#6855 Fix 3.7 on python 2
  .travis.yml
  CHANGELOG.rst
  cms/admin/placeholderadmin.py
  cms/admin/settingsadmin.py
  cms/context_processors.py
  cms/test_utils/testcases.py
  cms/tests/test_forms.py
  cms/tests/test_menu.py
  cms/tests/test_page.py
  cms/tests/test_signals.py
  cms/utils/check.py
  cms/utils/compat/dj.py
  cms/utils/conf.py
  cms/utils/permissions.py
  cms/utils/plugins.py
  cms/utils/urlutils.py
  docs/how_to/caching.rst
  docs/how_to/languages.rst
  docs/reference/configuration.rst
  menus/templatetags/menu_tags.py
  test_requirements/django-1.11.txt
  test_requirements/django-2.2.txt
  test_requirements/django-3.0.txt
  test_requirements/requirements_base.txt
Labels: backport
