Repository django-cms/django-cms, pull requests merged in 2021-04, with the labels that each got.

#7012 fixed readme quickstart section
  README.rst
Labels: status: ready to be merged

#7024 Changes in docs/contributing/code.rst
  CHANGELOG.rst
  docs/contributing/code.rst
Labels: status: ready for review

#6996 drop redundant 3.8.0rc1 compiled css files
  cms/static/cms/css/3.8.0rc1/cms.base.css
  cms/static/cms/css/3.8.0rc1/cms.pagetree.css
  cms/static/cms/css/3.8.0rc1/cms.welcome.css
  cms/static/cms/fonts/3.8.0rc1/django-cms-iconfont.woff2
  cms/static/cms/js/dist/3.8.0rc1/bundle.toolbar.min.js
Labels: status: ready for review, status: ready to be merged

#7020 Remove unused argument from `applications_page_check`
  cms/appresolver.py
Labels: status: ready for review, status: ready to be merged

#7025 Few docs improvements
  .readthedocs.yaml
  docs/introduction/01-install.rst
  docs/introduction/02-templates_placeholders.rst
Labels: status: ready to be merged
