Repository django-cms/django-cms, pull requests merged in 2021-05, with the labels that each got.

#6985 Fixes/flex page tree
  CHANGELOG.rst
  cms/static/cms/css/3.8.0/cms.pagetree.css
  cms/static/cms/sass/components/pagetree/_tree.scss
  cms/templates/admin/cms/page/tree/base.html
Labels: priority: medium, status: accepted, status: ready for review, status: ready to be merged

#7028 Use AUTH_USER_MODEL in signals
  cms/signals/__init__.py
Labels: priority: medium, status: accepted, status: ready to be merged

#7014 Fix doctest and updated relevant parts of docs config
  .gitignore
  docs/conf.py
  docs/reference/templatetags.rst
Labels: component: documentation, priority: high, status: ready for review

#6718 Improved performance of 'cms list plugins'.
  CHANGELOG.rst
  cms/management/commands/subcommands/list.py
  cms/tests/test_management.py
Labels: needs expert opinion

#7018 Add support for Django 3.2
  .github/workflows/test.yml
  CHANGELOG.rst
  cms/admin/pageadmin.py
  cms/cache/page.py
  cms/middleware/toolbar.py
  cms/tests/test_i18n.py
  cms/tests/test_po.py
  cms/tests/test_site.py
  cms/utils/compat/__init__.py
  cms/utils/compat/response.py
  cms/views.py
  manage.py
  test_requirements/django-3.2.txt
Labels: priority: high, status: ready for review

#6380 Fixed #3734 -- Automated check that PlaceholderFields use Placeholder…
  cms/tests/test_check.py
  cms/utils/check.py
Labels: kind: enhancement, status: accepted

#6956 Cache not invalidated when using a PlaceholderField outside the CMS #6912
  CHANGELOG.rst
  cms/models/placeholdermodel.py
  cms/tests/test_cache.py
Labels: priority: high, status: ready for review

#6958 Fix not checking slug uniqueness on page move
  CHANGELOG.rst
  cms/models/pagemodel.py
  cms/tests/test_page.py
  cms/utils/page.py
Labels: kind: bug

#6564 Allow recursive extend in rendering
  cms/test_utils/project/placeholderapp/templates/placeholder_tests/recursive_extend.html
  cms/test_utils/project/templates/placeholder_tests/recursive_extend.html
  cms/tests/test_placeholder.py
  cms/utils/placeholder.py
Labels: status: accepted

#6466 Fixed an issue where the wrong page title was returned
  CHANGELOG.rst
  cms/models/pagemodel.py
  cms/tests/test_cache.py
  cms/tests/test_extensions.py
  cms/tests/test_views.py
Labels: needs adjustments, status: accepted, status: ready for review

#7057 Docs: Update the python/django compatibility table
  docs/index.rst
Labels: component: documentation
