Repository django-cms/django-cms, pull requests merged in 2022-10, with the labels that each got.

#7339 fix: allow partially overriding CMS_CACHE_DURATIONS
  CHANGELOG.rst
  cms/utils/conf.py
  docs/reference/configuration.rst
Labels: 3.11

#7376 fix: Adjust paste label in pt-br locale
  cms/locale/pt_BR/LC_MESSAGES/django.po
Labels: 3.11

#7370 feat: Add support for tel: and mailto: URIs in Advanced Page Settings redirect field
  CHANGELOG.rst
  cms/forms/fields.py
  cms/forms/validators.py
Labels: status: ready to be merged, 3.11

#7406 docs: Plugin documentation typo
  docs/topics/plugins.rst
Labels: component: documentation

#7188 fix: Unlocalize page and node ids when rendering the page tree in the admin
  CHANGELOG.rst
  cms/admin/pageadmin.py
  cms/templates/admin/cms/page/tree/actions_dropdown.html
  cms/templates/admin/cms/page/tree/base.html
  cms/templates/admin/cms/page/tree/menu.html
  cms/templates/cms/toolbar/dragitem.html
  cms/tests/test_page_admin.py
Labels: status: ready to be merged, 3.11

#6866 fix: Clear page permission cache on page create
  CHANGELOG.rst
  cms/models/pagemodel.py
  cms/tests/test_add_page.py
Labels: status: ready to be merged, 3.11

#7407 fix: Changing color scheme resets session settings to defaults
  CHANGELOG.rst
  cms/static/cms/js/modules/cms.base.js
Labels: 3.11

#7408 ci: CMS v4: two tests to use self.assertEqual instead of self.assertTrue
  cms/tests/test_page.py
Labels: 4.x

#7414 perf: Don't count users when CMS_RAW_ID_USERS=True
  CHANGELOG.rst
  cms/admin/permissionadmin.py
  cms/tests/test_admin.py
  docs/reference/configuration.rst
Labels: component: performance, 3.11

#7413 fix: CMS check management command fixed [#7412]
  cms/utils/check.py
Labels: status: ready to be merged, 3.11

#7241 ci: Some tests misusing assertTrue for comparisons fix
  cms/tests/test_alias.py
  cms/tests/test_api.py
  cms/tests/test_publisher.py
  cms/tests/test_toolbar.py
Labels: 3.11

#7419 fix: Replacement of SEND_BROKEN_LINK_EMAILS by BrokenLinkEmailsMiddleware
  CHANGELOG.txt
  cms/templatetags/cms_tags.py
  cms/tests/test_templatetags.py
Labels: 4.x

#7411 Release note template
  docs/requirements.in
  docs/requirements.txt
  docs/upgrade/index.rst
  docs/upgrade/unreleased.rst
  docs/upgrade/version.rst.template
Labels: component: documentation, 4.x

#7418 feat: [CMS v4] Support for Django 4.1
  .github/workflows/test.yml
  CHANGELOG.txt
  README.rst
  cms/cms_config.py
  cms/management/commands/subcommands/base.py
  cms/middleware/language.py
  cms/models/pagemodel.py
  cms/models/titlemodels.py
  cms/signals/__init__.py
  cms/templatetags/cms_admin.py
  cms/templatetags/cms_js_tags.py
  cms/test_utils/project/customuserapp/models.py
  cms/test_utils/project/emailuserapp/models.py
  cms/test_utils/project/pluginapp/plugins/caching/cms_plugins.py
  cms/test_utils/testcases.py
  cms/tests/test_apphooks.py
  cms/tests/test_i18n.py
  cms/tests/test_migrations.py
  cms/tests/test_page_admin.py
  cms/tests/test_templatetags.py
  cms/utils/compat/__init__.py
  cms/utils/decorators.py
  cms/utils/request_ip_resolvers.py
  cms/views.py
  menus/apps.py
  menus/menu_pool.py
  menus/templatetags/menu_tags.py
  setup.py
  test_requirements/django-4.0.txt
  test_requirements/django-4.1.txt
  test_requirements/requirements_base.txt
Labels: 4.x

#7405 Fix page tree w/ empty page contents and language-aware adding of new page contents
  CHANGELOG.txt
  cms/forms/validators.py
  cms/templates/admin/cms/page/tree/actions_dropdown.html
  cms/templates/admin/cms/page/tree/base.html
  cms/templates/admin/cms/page/tree/menu.html
  cms/templatetags/cms_admin.py
  cms/tests/frontend/unit/fixtures/toolbar.html
  cms/tests/test_admin.py
  cms/utils/i18n.py
  docs/upgrade/unreleased.rst
Labels: 4.x

#7424 feat: Allow for Django 4.1 in setup.py
  setup.py
Labels: 4.x

#7410 fix: Added deprecation warning to `get_current_language()`
  CHANGELOG.rst
  cms/utils/i18n.py
Labels: 3.11

#7422 feat: add Python 3.11 support for Django CMS
  .github/workflows/docs.yml
  .github/workflows/test.yml
  CHANGELOG.rst
  setup.py
  test_requirements/databases.txt
Labels: 3.11
