Repository django-cms/django-cms, pull requests merged in 2022-11, with the labels that each got.

#7420 fix: Adds a deprecation warning for SEND_BROKEN_LINK_EMAILS
  CHANGELOG.rst
  cms/templatetags/cms_tags.py
  cms/utils/setup.py
Labels: 3.11

#7144 fix: Prefer titles matching request language
  CHANGELOG.rst
  cms/test_utils/testcases.py
  cms/tests/test_page.py
  cms/utils/page.py
Labels: 3.11

#7394 fix: CMS v4: Moving plugins between placeholders, plugin api
  cms/api.py
  cms/models/placeholdermodel.py
  cms/tests/test_api.py
  cms/tests/test_placeholder.py
Labels: 4.x

#7436 Add docstrings for autodoc
  cms/admin/forms.py
  cms/admin/placeholderadmin.py
  cms/api.py
  cms/app_base.py
  cms/cms_menus.py
  cms/cms_toolbars.py
  cms/constants.py
  cms/forms/fields.py
  cms/management/commands/subcommands/tree.py
  cms/menu_bases.py
  cms/models/fields.py
  cms/models/pagemodel.py
  cms/models/permissionmodels.py
  cms/models/placeholdermodel.py
  cms/models/pluginmodel.py
  cms/models/titlemodels.py
  cms/plugin_base.py
  cms/test_utils/fixtures/templatetags.py
  cms/tests/test_admin.py
  cms/tests/test_apphooks.py
  cms/tests/test_cache.py
  cms/tests/test_extensions.py
  cms/tests/test_forms.py
  cms/tests/test_i18n.py
  cms/tests/test_log_entries.py
  cms/tests/test_management.py
  cms/tests/test_menu.py
  cms/tests/test_menu_utils.py
  cms/tests/test_multilingual.py
  cms/tests/test_page.py
  cms/tests/test_page_admin.py
  cms/tests/test_placeholder.py
  cms/tests/test_sitemap.py
  cms/tests/test_templatetags.py
  cms/tests/test_toolbar.py
  cms/tests/test_views.py
  cms/toolbar/items.py
  cms/toolbar/toolbar.py
  cms/utils/plugins.py
  cms/wizards/helpers.py
  cms/wizards/wizard_base.py
  cms/wizards/wizard_pool.py
  menus/base.py
  menus/modifiers.py
Labels: component: documentation, 4.x

#7177 Optimize populating title cache for Page model.
  cms/models/pagemodel.py
  cms/tests/test_page.py
  cms/tests/test_plugins.py
  setup.cfg
Labels: 4.x

#7369 Change `TitleExtension` to `PageContentExtension`
  .github/workflows/linters.yml
  cms/admin/forms.py
  cms/admin/pageadmin.py
  cms/cms_menus.py
  cms/cms_toolbars.py
  cms/extensions/__init__.py
  cms/extensions/admin.py
  cms/extensions/extension_pool.py
  cms/extensions/models.py
  cms/extensions/toolbar.py
  cms/forms/validators.py
  cms/management/commands/subcommands/copy.py
  cms/models/__init__.py
  cms/models/contentmodels.py
  cms/models/pagemodel.py
  cms/page_rendering.py
  cms/plugin_rendering.py
  cms/templatetags/cms_admin.py
  cms/test_utils/project/extensionapp/admin.py
  cms/test_utils/project/extensionapp/cms_toolbars.py
  cms/test_utils/project/extensionapp/models.py
  cms/test_utils/testcases.py
  cms/tests/test_admin.py
  cms/tests/test_apphooks.py
  cms/tests/test_extensions.py
  cms/tests/test_multilingual.py
  cms/tests/test_page.py
  cms/tests/test_page_admin.py
  cms/tests/test_placeholder.py
  cms/tests/test_placeholder_admin.py
  cms/tests/test_plugins.py
  cms/tests/test_rendering.py
  cms/tests/test_templatetags.py
  cms/tests/test_toolbar.py
  cms/utils/check.py
  cms/views.py
  cms/wizards/wizard_base.py
  menus/menu_pool.py
  menus/templatetags/menu_tags.py
  menus/utils.py
Labels: 4.x
