Repository django-cms/django-cms, pull requests merged in 2023-06, with the labels that each got.

#7570 Fix: take csrf token from admin form or cms toolbar instead of cookie
  cms/static/cms/js/admin/actions.js
  cms/static/cms/js/modules/cms.pagetree.js
  cms/tests/frontend/unit/cms.structureboard.test.js
  package-lock.json
  package.json
Labels: 4.x

#7565 fix: create page wizard fails with Asian page titles/unicode slugs
  cms/admin/forms.py
  cms/admin/pageadmin.py
  cms/forms/wizards.py
  cms/static/cms/js/modules/slug.js
  cms/templates/admin/cms/page/change_form.html
  cms/tests/test_admin.py
Labels: needs to be forwardported, 3.11

#7572 fix: create page wizard fails with Asian page titles/unicode slugs
  CHANGELOG.rst
  cms/admin/forms.py
  cms/admin/pageadmin.py
  cms/forms/wizards.py
  cms/static/cms/js/modules/slug.js
  cms/templates/admin/cms/page/change_form.html
  cms/tests/test_admin.py
  cms/tests/test_log_entries.py
  cms/utils/apphook_reload.py
Labels: 4.x

#7577 fix: Unlocalize ids to avoid js errors for ids greater than 999
  cms/admin/pageadmin.py
  cms/templates/admin/cms/page/tree/actions_dropdown.html
  cms/templates/admin/cms/page/tree/base.html
  cms/templates/admin/cms/page/tree/menu.html
  cms/templates/cms/toolbar/dragitem.html
  cms/tests/test_page_admin.py
Labels: kind: bug, 4.x

#7580 fix: Borders for action buttons missing when using plain Django admin
  cms/static/cms/sass/cms.admin.scss
Labels: 4.x

#7578 fix: Add (back) navigation extenders to advanced settings
  cms/admin/forms.py
  cms/admin/utils.py
Labels: 4.x

#7587 fix: Mitigate performance hit due to deprecation warnings for v4.1
  cms/appresolver.py
  cms/templatetags/cms_tags.py
  cms/utils/moderator.py
  cms/utils/page.py
  cms/utils/plugins.py
  menus/menu_pool.py
Labels: 3.11

#7589 Fix #7588 overwrite widget attrs
  cms/admin/forms.py
Labels: 4.x

#7576 fix: page settings does focus on "page title" an optional field half-way down the form
  cms/static/cms/js/modules/slug.js
Labels: 4.x

#7591 fix: JS issues with running CMS under cypress
  cms/static/cms/js/modules/cms.base.js
  cms/static/cms/js/modules/cms.pagetree.js
  cms/static/cms/js/modules/cms.pagetree.stickyheader.js
  docs/spelling_wordlist
Labels: 3.11

#7596 fix: Sitemaps in v4 relied on availability of `PageUrl` instead of `PageContent`
  cms/sitemaps/cms_sitemap.py
Labels: 4.x

#7597 feat: Dark mode for v4 branch
  cms/cms_toolbars.py
  cms/static/cms/fonts/src/theme-auto.svg
  cms/static/cms/fonts/src/theme-dark.svg
  cms/static/cms/fonts/src/theme-light.svg
  cms/static/cms/js/modules/cms.base.js
  cms/static/cms/js/modules/cms.toolbar.js
  cms/static/cms/sass/cms.base.scss
  cms/static/cms/sass/cms.wizard.scss
  cms/static/cms/sass/components/_clipboard.scss
  cms/static/cms/sass/components/_dark-mode-toggle.scss
  cms/static/cms/sass/components/_dialog.scss
  cms/static/cms/sass/components/_dropdown.scss
  cms/static/cms/sass/components/_general.scss
  cms/static/cms/sass/components/_hovertooltip.scss
  cms/static/cms/sass/components/_iconography.scss
  cms/static/cms/sass/components/_modal.scss
  cms/static/cms/sass/components/_pluginpicker.scss
  cms/static/cms/sass/components/_reset.scss
  cms/static/cms/sass/components/_shortcuts.scss
  cms/static/cms/sass/components/_sideframe.scss
  cms/static/cms/sass/components/_structureboard.scss
  cms/static/cms/sass/components/_subnav.scss
  cms/static/cms/sass/components/_toolbar.scss
  cms/static/cms/sass/components/_tooltip.scss
  cms/static/cms/sass/components/pagetree/_dropdown.scss
  cms/static/cms/sass/components/pagetree/_tree.scss
  cms/static/cms/sass/mixins/_buttons.scss
  cms/static/cms/sass/mixins/_custom.scss
  cms/static/cms/sass/mixins/_zindex.scss
  cms/static/cms/sass/settings/_cms.scss
  cms/static/cms/sass/settings/_pagetree.scss
  cms/templates/admin/cms/page/tree/actions_dropdown.html
  cms/templates/cms/toolbar/items/dark_mode_toggle.html
  cms/templates/cms/toolbar/toolbar_javascript.html
  cms/tests/frontend/unit/cms.base.test.js
  cms/tests/test_toolbar.py
  cms/tests/test_views.py
  cms/utils/conf.py
Labels: 4.x

#7599 fix: update diff-dom and karma, run frontend tests on Chrome Headless
  cms/static/cms/js/modules/cms.structureboard.js
  cms/static/cms/js/modules/cms.toolbar.js
  cms/tests/frontend/karma.conf.js
  package-lock.json
  package.json
  webpack.config.js
Labels: component: frontend, 4.x

#7594 fix: Fixed RecursionError when extending templates
  cms/test_utils/project/placeholderapp/nested_placeholderapp/__init__.py
  cms/test_utils/project/placeholderapp/nested_placeholderapp/templates/placeholder_tests/nested_extend.html
  cms/test_utils/project/placeholderapp/templates/placeholder_tests/nested_extend.html
  cms/test_utils/project/templates/placeholder_tests/nested_extend.html
  cms/tests/test_placeholder.py
  cms/utils/placeholder.py
Labels: 4.x, 3.11

#7601 fix: try to upgrade node.js to 18
  .github/workflows/frontend.yml
  .nvmrc
Labels: 4.x
