Repository django-cms/django-cms, pull requests merged in 2023-10, with the labels that each got.

#7635 fix: Remove `can_publish` permission from django CMS 4 core
  cms/admin/forms.py
  cms/admin/permissionadmin.py
  cms/api.py
  cms/cache/permissions.py
  cms/migrations/0035_auto_20230822_2208.py
  cms/models/pagemodel.py
  cms/models/permissionmodels.py
  cms/static/cms/sass/components/_toolbar.scss
  cms/templates/admin/cms/page/permissions.html
  cms/test_utils/testcases.py
  cms/tests/test_admin.py
  cms/tests/test_permissions.py
  cms/tests/test_permmod.py
  cms/tests/test_toolbar.py
  cms/utils/page_permissions.py
Labels: component: permissions, 4.x

#7666 fix: change language url parameter to delete_language to prevent collision
  cms/admin/pageadmin.py
  cms/cms_toolbars.py
  cms/tests/test_admin.py
Labels: 3.11, needs port to 4.x

#7671 fix: When opening structure board page menu disappears or shows wrong page template
  .readthedocs.yaml
  cms/cms_toolbars.py
  cms/tests/test_views.py
  cms/views.py
Labels: 4.x

#7664 fix: preserve `view_class` in decorated views
  cms/tests/test_apphooks.py
  cms/utils/decorators.py
Labels: 3.11, needs port to 4.x

#7680 fix: #7662, add support for python 3.12 and upgrade github actions
  .github/workflows/codeql.yml
  .github/workflows/docs.yml
  .github/workflows/frontend.yml
  .github/workflows/lint-pr.yml
  .github/workflows/linters.yml
  .github/workflows/publish-to-live-pypi.yml
  .github/workflows/publish-to-test-pypi.yml
  .github/workflows/spelling.yml
  .github/workflows/test.yml
  CHANGELOG.rst
  cms/admin/forms.py
  cms/api.py
  cms/app_base.py
  cms/cms_menus.py
  cms/models/managers.py
  cms/models/permissionmodels.py
  cms/models/pluginmodel.py
  cms/signals/apphook.py
  cms/static/cms/js/select2/LICENSE
  cms/templatetags/cms_admin.py
  cms/templatetags/cms_tags.py
  cms/test_utils/project/app_using_non_feature/cms_config.py
  cms/test_utils/project/emailuserapp/forms.py
  cms/test_utils/project/mti_pluginapp/models.py
  cms/test_utils/project/sampleapp/cms_apps.py
  cms/test_utils/project/templates/placeholder_tests/outside.html
  cms/test_utils/project/templates/placeholder_tests/outside_sekizai.html
  cms/test_utils/project/templates/placeholder_tests/test_one.html
  cms/test_utils/project/templates/placeholder_tests/test_one_sekizai.html
  cms/test_utils/project/templates/placeholder_tests/test_two.html
  cms/test_utils/util/context_managers.py
  cms/tests/test_admin.py
  cms/tests/test_management.py
  cms/tests/test_menu.py
  cms/tests/test_nested_plugins.py
  cms/tests/test_permmod.py
  cms/tests/test_placeholder.py
  cms/tests/test_plugins.py
  cms/tests/test_signals.py
  cms/tests/test_templates.py
  cms/tests/test_templatetags.py
  cms/tests/test_toolbar.py
  cms/tests/test_wizards.py
  cms/utils/__init__.py
  cms/utils/apphook_reload.py
  cms/utils/compat/response.py
  cms/utils/conf.py
  cms/utils/helpers.py
  cms/utils/placeholder.py
  cms/views.py
  docs/conf.py
  docs/contributing/development-community.rst
  docs/how_to/frontend_models.rst
  docs/reference/templatetags.rst
  docs/requirements.in
  docs/requirements.txt
  docs/topics/commonly_used_plugins.rst
  docs/upgrade/4.0.rst
  setup.cfg
  test_requirements/requirements_base.txt
Labels: 4.x

#7657 fix: avoid InvalidCacheKey (memcached) for key-length ~249
  cms/cache/placeholder.py
Labels: status: ready to be merged, 3.11, needs port to 4.x

#7681 fix: Update transifex pull strings script for v3 in alignment with v4
  scripts/transifex-pull-strings
Labels: 3.11

#7679 fix: `.load` jQuery method erroneously replaced by `.on('load')`
  cms/admin/forms.py
  cms/admin/permissionadmin.py
  cms/api.py
  cms/cache/permissions.py
  cms/migrations/0035_auto_20230822_2208.py
  cms/models/managers.py
  cms/models/pagemodel.py
  cms/models/permissionmodels.py
  cms/static/cms/js/modules/cms.changeform.js
  cms/templates/admin/cms/page/permissions.html
  cms/templatetags/cms_admin.py
  cms/test_utils/testcases.py
  cms/tests/test_admin.py
  cms/tests/test_permissions.py
  cms/tests/test_permmod.py
  cms/tests/test_toolbar.py
  cms/utils/page_permissions.py
Labels: 4.x
