Repository django-cms/django-cms, pull requests merged in 2024-07, with the labels that each got.

#7943 feat: Performant permission calculation for pages
  cms/admin/pageadmin.py
  cms/cms_menus.py
  cms/menu_bases.py
  cms/models/managers.py
  cms/models/permissionmodels.py
  cms/templates/admin/cms/page/tree/menu.html
  cms/tests/test_page_admin.py
  cms/tests/test_permissions.py
  cms/tests/test_permmod.py
  cms/utils/mail.py
  cms/utils/page_permissions.py
  cms/utils/permissions.py
Labels: component: permissions, component: performance

#7955 fix: Show pages titles using fallback languages in pagetree
  cms/admin/pageadmin.py
  cms/templates/admin/cms/page/tree/menu.html
  cms/templatetags/cms_admin.py
  cms/tests/test_templatetags.py
Labels: needs to be backported

#7954 fix: Fail silently when rendering a placeholder on a missing toolbar object
  .github/workflows/new_contributor_pr.yml
  cms/plugin_rendering.py
  cms/tests/test_placeholder.py
  cms/utils/placeholder.py
Labels: needs to be backported

#7850 feat: Headless readiness
  .editorconfig
  cms/admin/pageadmin.py
  cms/admin/placeholderadmin.py
  cms/appresolver.py
  cms/cms_toolbars.py
  cms/models/contentmodels.py
  cms/models/pagemodel.py
  cms/page_rendering.py
  cms/plugin_base.py
  cms/static/cms/js/modules/cms.plugins.js
  cms/static/cms/js/modules/cms.structureboard.js
  cms/static/cms/sass/components/_structureboard.scss
  cms/static/cms/sass/components/_toolbar.scss
  cms/templates/admin/cms/page/close_frame.html
  cms/templates/cms/headless/placeholder.html
  cms/templates/cms/toolbar/dragbar.html
  cms/templates/cms/toolbar/dragitem.html
  cms/templates/cms/toolbar/render_plugin_block.html
  cms/templates/cms/toolbar/structure.html
  cms/templates/cms/toolbar/toolbar_javascript.html
  cms/templates/cms/welcome.html
  cms/templates/cms/wizards/create.html
  cms/templates/cms/wizards/start.html
  cms/templatetags/cms_tags.py
  cms/tests/test_wizards.py
  cms/toolbar/toolbar.py
  cms/toolbar/utils.py
  cms/utils/check.py
  cms/utils/conf.py
  cms/utils/page.py
  cms/utils/placeholder.py
  cms/views.py
  docs/how_to/21-headless.rst
  docs/how_to/index.rst
  docs/reference/configuration.rst
Labels: status: ready for review

#7967 fix: template tag `get_admin_url_for_language` did not return the latest page content
  cms/admin/forms.py
  cms/admin/pageadmin.py
  cms/templatetags/cms_admin.py
Labels: needs to be backported

#7972 docs: add documentation for search
  docs/explanation/publishing.rst
  docs/explanation/searchdocs.rst
Labels: component: documentation
