Repository django-cms/django-cms, pull requests merged in 2024-11, with the labels that each got.

#8056 fix: added redirect message when in editing a redirect toolbar object
  cms/tests/test_views.py
  cms/views.py
Labels: needs to be backported

#8060 chore: Fixed randomly failing Postgres tests
  .github/workflows/test.yml
  cms/models/placeholdermodel.py
  cms/models/pluginmodel.py
  cms/tests/test_placeholder.py
Labels: needs to be backported

#8057 feat: Updated welcome page
  cms/models/fields.py
  cms/plugin_base.py
  cms/static/cms/sass/components/_welcome.scss
  cms/templates/cms/welcome.html
Labels: needs to be backported

#8052 fix: Menus crashed when unexpected page content was present
  .github/workflows/test.yml
  cms/admin/pageadmin.py
  cms/cms_menus.py
  cms/models/managers.py
  cms/models/pagemodel.py
  cms/models/permissionmodels.py
  cms/plugin_rendering.py
  cms/templates/cms/welcome.html
  cms/templatetags/cms_admin.py
  cms/tests/test_admin.py
  cms/tests/test_extensions.py
  cms/tests/test_i18n.py
  cms/tests/test_management.py
  cms/tests/test_page_admin.py
  cms/tests/test_permmod.py
  cms/tests/test_placeholder.py
  cms/tests/test_plugins.py
  cms/tests/test_templatetags.py
  cms/tests/test_views.py
  cms/toolbar/utils.py
  cms/utils/permissions.py
  cms/views.py
Labels: 4.1

#8054 fix: Handle cms command raising error
  cms/management/commands/subcommands/base.py
  cms/tests/test_management.py
Labels: status: ready to be merged

#8059 fix: Fall back to class name when app name is None
  cms/apphook_pool.py
  cms/tests/test_apphooks.py
  cms/tests/test_check.py
  cms/utils/check.py
Labels: status: ready to be merged

#8064 fix: Sites menu was empty in the page tree
  cms/admin/pageadmin.py
  cms/tests/test_admin.py
Labels: needs to be backported, 4.2

#8067 fix: Grouper admin raised AttributeError when used outside the admin views
  cms/admin/pageadmin.py
  cms/admin/utils.py
  cms/forms/validators.py
  cms/models/pagemodel.py
  cms/tests/test_admin.py
  cms/tests/test_grouper_admin.py
  cms/tests/test_log_entries.py
  cms/utils/placeholder.py
Labels: needs to be backported, 4.2
