Repository django-cms/django-cms, pull requests merged in 2024-02, with the labels that each got.

#7750 feat: add versioned deprecation warnings
  cms/admin/placeholderadmin.py
  cms/api.py
  cms/cms_menus.py
  cms/cms_plugins.py
  cms/cms_toolbars.py
  cms/exceptions.py
  cms/extensions/toolbar.py
  cms/forms/fields.py
  cms/forms/wizards.py
  cms/templatetags/cms_alias_tags.py
  cms/tests/test_extensions.py
  cms/utils/compat/warnings.py
  menus/base.py
  menus/menu_pool.py
  menus/models.py
  menus/modifiers.py
  menus/utils.py
  pyproject.toml
Labels: 4.x

#7827 docs: Update to reflect new, simplified contributing process
  docs/contributing/development-community.rst
Labels: component: documentation

#7823 docs: remove git switch for quickstart
  docs/introduction/01-install.rst
Labels: status: ready to be merged

#7819 fix: `./manage.py cms check` showed wrong error message
  cms/utils/check.py
Labels: status: ready to be merged

#7781 fix: render content in place `redirect_on_fallback` is False
  cms/plugin_rendering.py
  cms/test_utils/testcases.py
  cms/tests/test_i18n.py
  cms/tests/test_multilingual.py
  cms/tests/test_plugins.py
  cms/utils/__init__.py
  cms/views.py
Labels: status: ready to be merged

#7814 fix: Delete orphaned plugin management command for django CMS 4
  cms/management/commands/subcommands/delete_orphaned_plugins.py
  cms/tests/test_management.py
Labels: status: ready for review
