Repository django-cms/django-cms, pull requests merged in 2024-05, with the labels that each got.

#7902 fix: Set toolbar direction based on toolbar language
  cms/static/cms/js/modules/cms.modal.js
  cms/static/cms/sass/cms.base.scss
  cms/static/cms/sass/cms.wizard.scss
  cms/static/cms/sass/components/_modal.scss
  cms/static/cms/sass/components/_sideframe.scss
  cms/static/cms/sass/components/_structureboard.scss
  cms/static/cms/sass/components/_toolbar.scss
  cms/static/cms/sass/components/pagetree/_tree.scss
  cms/static/cms/sass/libs/_rtl_patch.scss
  cms/static/cms/sass/settings/_cms.scss
  cms/templates/cms/toolbar/toolbar.html
  cms/test_utils/testcases.py
  cms/toolbar/toolbar.py
Labels: 4.1

#7916 chore: Cherry-pick changes to `develop` branch into `release/3.11.x`
  .github/workflows/docs.yml
  .github/workflows/frontend.yml
  .github/workflows/lint-pr.yml
  .github/workflows/linters.yml
  .github/workflows/new_contributor_pr.yml
  .github/workflows/test.yml
  cms/middleware/toolbar.py
  cms/static/cms/img/pagetree/tree-li-drag.gif
  cms/static/cms/js/modules/cms.pagetree.js
  cms/static/cms/sass/components/pagetree/_dropdown.scss
  cms/static/cms/sass/components/pagetree/_legend.scss
  cms/static/cms/sass/components/pagetree/_tree.scss
  cms/static/cms/sass/settings/_pagetree.scss
  cms/templates/admin/cms/page/tree/base.html
  cms/templates/admin/cms/page/tree/legend.html
  cms/templates/admin/cms/page/tree/menu.html
  cms/tests/test_toolbar.py
Labels: 3.11

#7921 fix: Allow viewing page settings even if page cannot be changed
  cms/admin/pageadmin.py
  cms/tests/test_permmod.py
Labels: 4.1

#7924 fix: Versioning-safe implementation of placeholder inheritance
  cms/plugin_rendering.py
  cms/toolbar/toolbar.py
Labels: 4.1

#7920 fix: Only switch to structure endpoint on viewport breakpoint if in edit mode
  cms/static/cms/js/modules/cms.structureboard.js
Labels: needs to be backported, 4.1

#7919 feat: Reintroduce `default_plugins` setting
  cms/tests/test_permmod.py
  cms/tests/test_placeholder.py
  cms/tests/test_rendering.py
  cms/utils/plugins.py
Labels: 4.1

#7868 fix: #7859: allow special characters in page title
  cms/templatetags/cms_tags.py
  cms/tests/test_templatetags.py
Labels: needs to be backported, 4.1

#7929 docs: Improve explanation on how to use templates with django CMS
  docs/how_to/04-templates.rst
  docs/introduction/01-install.rst
  setup.cfg
Labels: component: documentation
