Repository django-cms/django-cms, pull requests merged in 2024-10, with the labels that each got.

#8022 fix: Accept legacy action names for page permission check
  cms/tests/test_permissions.py
  cms/utils/permissions.py
Labels: 3.11

#8021 fix: Accept legacy action names for page permission check
  cms/admin/pageadmin.py
  cms/models/permissionmodels.py
  cms/test_utils/testcases.py
  cms/tests/test_extensions.py
  cms/tests/test_permissions.py
  cms/tests/test_placeholder.py
  cms/tests/test_plugins.py
  cms/tests/test_views.py
  cms/utils/page_permissions.py
  cms/utils/permissions.py
  docs/upgrade/4.2.0.rst
Labels: 4.1, 4.2

#8031 fix: Sitemap: Return a QuerySet in CMSSitemap.items()
  cms/sitemaps/cms_sitemap.py
  cms/tests/test_sitemap.py
Labels: needs to be backported

#8033 fix: Improve UX when page content is missing in selected language
  cms/static/cms/sass/components/pagetree/_tree.scss
Labels: needs to be backported

#8041 fix: X frame options added to page settings form
  cms/admin/forms.py
  cms/migrations/0029_create_title_fields_and_url_model.py
  cms/models/contentmodels.py
  cms/page_rendering.py
  cms/tests/test_admin.py
Labels: needs to be backported, 4.2

#7999 fix: Issue 7997 remove edit page dialog
  cms/cms_toolbars.py
Labels: 4.2
