Repository django-cms/django-cms, pull requests merged in 2024-01, with the labels that each got.

#7747 fix: #7745 -- permission handling when deleting page
  cms/admin/pageadmin.py
Labels: status: ready to be merged, 4.x, needs port to 4.1.x

#7744 fix: Add `--fix-paths` option to `./manage.py cms fix-tree`
  cms/management/commands/subcommands/tree.py
  cms/models/pluginmodel.py
  setup.py
Labels: 3.11

#7740 fix: make messages readable in dark mode, let user close long messages
  cms/static/cms/js/modules/cms.messages.js
  cms/static/cms/sass/settings/_cms.scss
Labels: 4.x, needs port to 4.1.x

#7719 feat: Add bot to remind to not squash merges into release/* branches
  .github/workflows/releases.yml
Labels: 3.11

#7739 fix: readable messages in dark-mode
  cms/static/cms/sass/settings/_cms.scss
Labels: 3.11
