Repository django-cms/django-cms, pull requests merged in 2025-02, with the labels that each got.

#8120 feat: Optimize DB queries for edit and structure endpoints
  cms/models/fields.py
  cms/models/managers.py
  cms/models/placeholdermodel.py
  cms/models/pluginmodel.py
  cms/plugin_base.py
  cms/plugin_pool.py
  cms/plugin_rendering.py
  cms/signals/log_entries.py
  cms/static/cms/sass/libs/_iconfont.scss
  cms/test_utils/project/placeholderapp/models.py
  cms/test_utils/project/sampleapp/models.py
  cms/test_utils/testcases.py
  cms/tests/test_admin.py
  cms/tests/test_cache.py
  cms/tests/test_i18n.py
  cms/tests/test_management.py
  cms/tests/test_placeholder.py
  cms/tests/test_placeholder_admin.py
  cms/tests/test_placeholder_app_admin.py
  cms/tests/test_plugin_renderers.py
  cms/tests/test_templatetags.py
  cms/tests/test_toolbar.py
  cms/toolbar/toolbar.py
  cms/toolbar/utils.py
  cms/utils/__init__.py
  cms/utils/permissions.py
  cms/utils/placeholder.py
  cms/utils/plugins.py
  cms/utils/urlutils.py
  cms/views.py
  docs/reference/configuration.rst
  docs/upgrade/4.2.0.rst
  menus/utils.py
  test_requirements/databases.txt
Labels: 4.2

#8094 fix: Respect setting CMS_ DEFAULT_IN_NAVIGATION
  cms/admin/forms.py
  cms/utils/conf.py
  docs/reference/configuration.rst
Labels: 4.2

#7905 fix: #7904 - `manage.py cms fixtree` did not fix PageUrl model
  cms/management/commands/subcommands/tree.py
  cms/tests/test_management.py
Labels: needs tests, needs to be backported, 4.2

#8131 fix: Allow frontend editing of page title fields
  cms/admin/pageadmin.py
  cms/tests/test_admin.py
Labels: needs to be backported, 4.1, 4.2

#8109 feat: Allow for CSP - remove inline scripts from edit endpoint markup
  cms/constants.py
  cms/plugin_rendering.py
  cms/static/cms/js/admin.base.js
  cms/static/cms/js/modules/cms.messages.js
  cms/static/cms/js/modules/cms.plugins.js
  cms/static/cms/js/toolbar.js
  cms/templates/admin/cms/page/change_form.html
  cms/templates/admin/cms/page/close_frame.html
  cms/templates/admin/cms/page/plugin/change_form.html
  cms/templates/cms/toolbar/plugin.html
  cms/templates/cms/toolbar/toolbar_javascript.html
  cms/templates/cms/toolbar/toolbar_with_structure.html
  cms/templates/cms/wizards/base.html
  cms/templatetags/cms_js_tags.py
  cms/tests/frontend/unit/cms.messages.test.js
  cms/tests/test_placeholder.py
  cms/tests/test_toolbar.py
  docs/upgrade/4.2.0.rst
  package-lock.json
Labels: 4.2

#8137 fix: Page menu disappeared in edit or structure endpoints when refreshing the toolbar
  cms/admin/forms.py
  cms/admin/settingsadmin.py
  cms/tests/test_placeholder_admin.py
Labels: needs to be backported, 4.2
