Repository django-cms/django-cms, pull requests merged in 2025-01, with the labels that each got.

#8115 fix: Placeholder page getter failed for unpublished pages
  cms/models/placeholdermodel.py
Labels: needs to be backported, 4.2

#8122 fix: Use correct `changed_date` of page content in sitemap
  cms/sitemaps/cms_sitemap.py
  cms/tests/test_page.py
  cms/tests/test_plugins.py
Labels: kind: bug, needs to be backported

#8125 fix: Use PageContent.changed_date for sitemap lastmod
  cms/sitemaps/cms_sitemap.py
  cms/tests/test_page.py
  cms/tests/test_plugins.py
  test_requirements/databases.txt
Labels: backport, 4.1

#8111 fix: Added the new delete confirmation for pages also to delete translation
  cms/admin/pageadmin.py
  cms/tests/test_admin.py
  cms/tests/test_page_admin.py
  docs/upgrade/4.2.0.rst
Labels: 4.2
